---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: ${NAMESPACE}
  labels:
    app: nodejs
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs
    spec:
      containers:
      - image: ${IMAGE_NAME}
        ports:
          - containerPort: 3000
        name: nodejs
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: ${NAMESPACE}
  creationTimestamp: null
  labels:
    app: nodejs
  name: nodejs
spec:
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30007
  selector:
    app: nodejs
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ${NAMESPACE}
  name: nodejs
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs
            port:
              number: 3000
